### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by reidarsollid** [akonwi/git-plus#137]
Uncaught Error: Pane has been destroyed

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.3.1

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:579

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:579:15)
  at git.cmd.stdout (/Users/reidar/.atom/packages/git-plus/lib/models/git-commit.coffee:111:33)
  at exit (/Users/reidar/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:52:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:105:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```

/cc @atom/core

**Comment by akonwi** [comment]
Can you share the steps to reproduce please?

**Comment by reidarsollid** [comment]
Well, I changed this file 
https://github.com/reidarsollid/RustyCage/blob/master/pom.xml
And used Git plus from the Packages menue. First add and then commit. When I saved the commit message it crashed, normally this works fine.

**Comment by akonwi** [comment]
I've updated atom and have been trying to recreate this but with no luck. Are you still having the problem?

**Comment by reidarsollid** [comment]
It happend only once, I will get back to you if it happens again.
