### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Users/Leeszi/workspace/MyProjects/Exam-Server/Exam-Protocol/.git'

### ISSUE THREAD

**Issue by lazyjean** [akonwi/git-plus#154]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.3.8

### Stack Trace

Uncaught Error: EEXIST, file already exists '/Users/Leeszi/workspace/MyProjects/Exam-Server/Exam-Protocol/.git'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:76

Error: EEXIST, file already exists '/Users/Leeszi/workspace/MyProjects/Exam-Server/Exam-Protocol/.git'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:679:18)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:55:12)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:227:14)
  at GitCommit.module.exports.GitCommit.prepFile (/Users/Leeszi/.atom/packages/git-plus/lib/models/git-commit.coffee:75:8)
  at git.cmd.stdout (/Users/Leeszi/.atom/packages/git-plus/lib/models/git-commit.coffee:62:30)
  at exit (/Users/Leeszi/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -1:46.6 command-palette:toggle (atom-text-editor.editor.mini)
     -1:45.6 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:45.6 core:cancel (atom-text-editor.editor.mini)
     -1:13.1 window:toggle-full-screen (div.settings-view.pane-item)
     -0:35.1 core:save (atom-text-editor.editor)
     -0:33.3 command-palette:toggle (atom-text-editor.editor)
 15x -0:29.6 core:move-down (atom-text-editor.editor.mini)
     -0:24.9 core:move-up (atom-text-editor.editor.mini)
     -0:24.5 core:confirm (atom-text-editor.editor.mini)
     -0:24.3 git-plus:commit (atom-text-editor.editor)
     -0:20.8 core:save (atom-text-editor.editor)
  3x -0:14.3 core:close (atom-text-editor.editor)
     -0:09.5 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:04.4 core:move-down (atom-text-editor.editor.mini)
     -0:00.7 core:confirm (atom-text-editor.editor.mini)
     -0:00.7 git-plus:add-all-and-commit (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "keybinding-resolver",
      "vim-mode"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.14.0
color-picker, v1.4.4
git-log, v0.2.0
git-plus, v4.3.8
git-projects, v1.7.0
language-thrift, v1.0.0
linter, v0.11.1
minimap, v4.0.2
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by akonwi** [comment]
This should be fixed in the latest update.
