### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by Victorystick** [akonwi/git-plus#155]
It doesn't seem to happen every time.

1. Edit document
2. Save document
3. Add and Commit (Got the same issue at this point.)
4. Push (Issue)

5. Push (Worked fine)

**Atom Version**: 0.176.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/eoskseg/.atom/packages/git-plus/lib/git.coffee:138

TypeError: Cannot read property 'getPath' of undefined
  at dir (/home/eoskseg/.atom/packages/git-plus/lib/git.coffee:138:63)
  at Object.gitCmd [as cmd] (/home/eoskseg/.atom/packages/git-plus/lib/git.coffee:17:18)
  at gitPush (/home/eoskseg/.atom/packages/git-plus/lib/models/git-push.coffee:5:7)
  at atom-workspace.<anonymous> (/home/eoskseg/.atom/packages/git-plus/lib/git-plus.coffee:85:63)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -3:24.9 core:backspace (atom-text-editor.editor)
     -3:24.2 editor:newline (atom-text-editor.editor)
     -3:23.7 core:save (atom-text-editor.editor)
     -3:23.2 latex:build (atom-text-editor.editor)
     -3:13.6 git-plus:add-and-commit (atom-text-editor.editor)
  2x -3:04.1 core:backspace (atom-text-editor.editor)
     -2:57.3 editor:newline (atom-text-editor.editor)
     -2:56.9 core:backspace (atom-text-editor.editor)
     -2:56.5 core:save (atom-text-editor.editor)
     -2:53.7 core:close (div.pdf-view)
     -1:09.8 latex:build (atom-text-editor.editor)
     -0:18.5 command-palette:toggle (div.pdf-view)
     -0:09.7 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
 12x -0:08.6 core:backspace (atom-text-editor.editor.mini)
     -0:00.5 core:confirm (atom-text-editor.editor.mini)
     -0:00.5 git-plus:push (div.pdf-view)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.4.8
git-plus, v4.4.0
language-bil, v0.0.0
language-latex, v0.4.1
language-ocaml, v1.1.0
language-x86asm, v0.4.0
latex, v0.16.1
minimap, v4.0.2
minimap-git-diff, v3.1.1
pdf-view, v0.15.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by Qnzvna** [comment]
I have the same issue:

1. Add all and commit (issue)
Then It doesn't push.

**Atom Version**: 0.176.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/abel/.atom/packages/git-plus/lib/git.coffee:138

TypeError: Cannot read property 'getPath' of undefined
  at Object.dir (/home/abel/.atom/packages/git-plus/lib/git.coffee:138:63)
  at GitCommit.module.exports.GitCommit.dir (/home/abel/.atom/packages/git-plus/lib/models/git-commit.coffee:26:11)
  at GitCommit.module.exports.GitCommit.filePath (/home/abel/.atom/packages/git-plus/lib/models/git-commit.coffee:31:27)
  at GitCommit.module.exports.GitCommit.prepFile (/home/abel/.atom/packages/git-plus/lib/models/git-commit.coffee:64:23)
  at git.cmd.stdout (/home/abel/.atom/packages/git-plus/lib/models/git-commit.coffee:51:30)
  at exit (/home/abel/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -7:31.8 find-and-replace:show (atom-text-editor.editor)
  3x -7:30.6 core:confirm (atom-text-editor.editor.mini)
     -7:25.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -7:25.0 core:cancel (atom-text-editor.editor.mini)
  5x -7:20.1 core:backspace (atom-text-editor.editor)
     -6:05.1 core:save (atom-text-editor.editor)
  3x -3:41.2 core:backspace (atom-text-editor.editor)
     -3:38.5 core:save (atom-text-editor.editor)
  2x -0:58.3 editor:newline (atom-text-editor.editor)
     -0:47.6 core:save (atom-text-editor.editor)
  5x -0:35.2 core:backspace (atom-text-editor.editor)
     -0:12.6 core:save (atom-text-editor.editor)
     -0:11.2 command-palette:toggle (atom-text-editor.editor)
  3x -0:07.5 core:move-down (atom-text-editor.editor.mini)
     -0:06.8 core:confirm (atom-text-editor.editor.mini)
     -0:04.9 git-plus:add-all-and-commit (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "bookmarks",
      "dev-live-reload",
      "exception-reporting",
      "fuzzy-finder",
      "grammar-selector",
      "image-view",
      "incompatible-packages",
      "metrics",
      "open-on-github",
      "package-generator",
      "release-notes",
      "update-package-dependencies",
      "welcome",
      "remote-atom",
      "autocomplete",
      "linter-jscs"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.11
git-plus, v4.4.0
linter, v0.11.1
linter-php, v0.0.11
minimap, v4.1.0
monokai, v0.12.0
php-twig, v3.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by otzy007** [comment]
[Enter steps to reproduce below:]
Happened to me twice. If I close atom and start it again this doesn't happened anymore

1. Add some files

2. Commit

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/andrei/.atom/packages/git-plus/lib/git.coffee:138

TypeError: Cannot read property 'getPath' of undefined
  at Object.dir (/Users/andrei/.atom/packages/git-plus/lib/git.coffee:138:12)
  at GitCommit.module.exports.GitCommit.dir (/Users/andrei/.atom/packages/git-plus/lib/models/git-commit.coffee:26:11)
  at GitCommit.module.exports.GitCommit.filePath (/Users/andrei/.atom/packages/git-plus/lib/models/git-commit.coffee:31:27)
  at GitCommit.module.exports.GitCommit.prepFile (/Users/andrei/.atom/packages/git-plus/lib/models/git-commit.coffee:64:23)
  at git.cmd.stdout (/Users/andrei/.atom/packages/git-plus/lib/models/git-commit.coffee:51:30)
  at exit (/Users/andrei/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  2x -4:03.5 editor:newline (atom-text-editor.editor)
  8x -4:00.8 core:undo (atom-text-editor.editor)
  2x -1:37.6 core:redo (atom-text-editor.editor.autocomplete-active)
  5x -1:35.8 core:undo (atom-text-editor.editor.autocomplete-active)
 16x -1:32.7 core:redo (atom-text-editor.editor.autocomplete-active)
  7x -1:30.7 core:undo (atom-text-editor.editor.autocomplete-active)
  4x -1:20.8 core:delete (atom-text-editor.editor.autocomplete-active)
     -1:17.6 core:save (atom-text-editor.editor.autocomplete-active)
  2x -0:08.1 git-plus:add (atom-text-editor.editor.autocomplete-active)
     -0:01.4 git-plus:commit (atom-text-editor.editor.autocomplete-active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
RubyMotion, v0.6.2
autocomplete-emojis, v0.7.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.0.12
cucumber, v0.4.1
git-log, v0.2.0
git-plus, v4.4.1
github-issues, v0.3.0
language-latex, v0.4.1
language-rust, v0.3.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by akonwi** [comment]
I'm assuming this isn't a problem anymore so I'll close this.
