### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by jiep** [akonwi/git-plus#164]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.8

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/src/workspace.js:510

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:399:109)
  at File.module.exports.File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:108:14)
  at File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:88:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1089:44)
  at TextBuffer.module.exports.TextBuffer.setPath (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:281:14)
  at new TextBuffer (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:381:16)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:355:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:309:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:418:19)
  at GitCommit.module.exports.GitCommit.showFile (/home/jose/.atom/packages/git-plus/lib/models/git-commit.coffee:77:8)
  at GitCommit.module.exports.GitCommit.prepFile (/home/jose/.atom/packages/git-plus/lib/models/git-commit.coffee:70:6)
  at git.cmd.stdout (/home/jose/.atom/packages/git-plus/lib/models/git-commit.coffee:51:30)
  at exit (/home/jose/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1068:12)

```

### Commands

```
  2x -7:06.1 core:move-right (atom-text-editor.editor.autocomplete-active)
  2x -7:04.9 core:save (atom-text-editor.editor.autocomplete-active)
     -6:48.0 core:backspace (atom-text-editor.editor.autocomplete-active)
     -6:46.4 core:save (atom-text-editor.editor.autocomplete-active)
     -6:21.3 core:backspace (atom-text-editor.editor.autocomplete-active)
     -6:20.4 core:save (atom-text-editor.editor.autocomplete-active)
     -0:30.1 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:27.0 core:confirm (atom-text-editor.editor.mini)
     -0:23.0 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.9 core:confirm (atom-text-editor.editor.mini)
     -0:18.4 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.0 core:confirm (atom-text-editor.editor.mini)
     -0:13.6 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.2 core:confirm (atom-text-editor.editor.mini)
     -0:09.8 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.2 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.3
color-picker, v1.4.4
git-plus, v4.4.8
language-javascript, v0.60.0
language-latex, v0.4.1
language-php, v0.21.0
latex, v0.18.1
linter, v0.12.0
minimap, v4.1.3
texlicious, v0.3.9

# Dev
No dev packages
```

/cc @atom/core

**Comment by akonwi** [comment]
Can you provide steps to reproduce this problem?
