### ISSUE TITLE
Uncaught ReferenceError: a is not defined in git-plus/lib/models/git-branch.coffee:35

### ISSUE THREAD

**Issue by svanharmelen** [akonwi/git-plus#175]
New bug in latest version of git-plus, v4.4.11 See related inline comments [here](https://github.com/akonwi/git-plus/commit/1a963980fa48e14be4d505adb31874e083859dd8)

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.11

### Stack Trace

Uncaught ReferenceError: a is not defined

```
At /Users/svanharmelen/.atom/packages/git-plus/lib/models/git-branch.coffee:35

ReferenceError: a is not defined
  at atom-text-editor.disposables.add.atom.commands.add.core:confirm (/Users/svanharmelen/.atom/packages/git-plus/lib/models/git-branch.coffee:35:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

**Comment by despairblue** [comment]
:+1:

**Comment by svanharmelen** [comment]
Thanks for the quick update/fix!

**Comment by akonwi** [comment]
No problem
