### ISSUE TITLE
Failed to activate the git-plus package

### ISSUE THREAD

**Issue by fbbdev** [akonwi/git-plus#176]
Steps to reproduce:
1. Install atom v.0.190.0
2. Install git-plus package
3. Run atom in 1.0 API preview mode: `atom -1`

**Atom Version**: 0.190.0
**System**: linux 3.19.3-200.fc21.x86_64
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.13
### Stack Trace

Failed to activate the git-plus package

```
At undefined is not a function

TypeError: undefined is not a function
  at dir (/home/fabio/.atom/packages/git-plus/lib/git.coffee:147:58)
  at gitCmd (/home/fabio/.atom/packages/git-plus/lib/git.coffee:17:18)
  at Object.gitRefreshIndex [as refresh] (/home/fabio/.atom/packages/git-plus/lib/git.coffee:89:3)
  at Object.module.exports.activate (/home/fabio/.atom/packages/git-plus/lib/git-plus.coffee:73:11)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:19)
  at /usr/share/atom/resources/app/src/package.js:206:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:152:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:199:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:435:21)
  at /usr/share/atom/resources/app/src/package-manager.js:419:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:302:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:414:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:395:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:634:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:54:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.5.6
autocomplete-css, v0.6.0
autocomplete-glsl, v0.2.0
autocomplete-haskell, v0.2.1
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-plus-jedi, v0.0.9
bezier-curve-editor, v0.6.6
color-picker, v1.6.0
fancy-new-file, v0.7.0
format-sql, v0.2.0
git-blame, v0.4.0
git-history, v2.5.0
git-log, v0.3.0
highlight-line, v0.10.1
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-python-pep8, v0.2.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
ogg-preview, v0.2.0
pdf-view, v0.17.0
project-manager, v1.15.5
quick-move-file, v0.7.0
scroll-sync, v0.1.1
svg-preview, v0.5.1
task-list, v0.7.0

# Dev
No dev packages
```

**Comment by akonwi** [comment]
There's a new branch called '1.0.0' with some big changes to keep up with atom as it reaches the 1.0 release. You can clone that branch into the packages directory of atom and run `apm install` inside the new directory to use that version instead. I'd love the feedback

**Comment by qayshp** [comment]
v4.5.0 of git-plus seems to resolve this for me.

**Comment by akonwi** [comment]
I'm assuming this isn't an issue anymore

**Comment by SecondeJK** [comment]
1.8 Atom and gitplus  is seeing this crop up again.

**Comment by EQuimper** [comment]
Atom 1.11.2
Git-Plus 5.23.0
Mac Sierra 10.12.1

Same error. Can't use it anymore

**Comment by akonwi** [comment]
@EQuimper Can you share the stack trace you get?

**Comment by EQuimper** [comment]
@akonwi 
```
Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/emanuelquimper/.atom/packages/git-plus/lib/git-plus.coffee:2:7)
    at Object.<anonymous> (/Users/emanuelquimper/.atom/packages/git-plus/lib/git-plus.coffee:1:1)
    at Module._compile (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Users/emanuelquimper/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28
```

**Comment by EQuimper** [comment]
I've just updated with the new Release 5.23.2 everything work now

**Comment by vicentimartins** [comment]
After the last update, I get this error.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.27.0


### Stack Trace

Failed to activate the git-plus package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/vicentimartins/.atom/packages/git-plus/lib/git-plus.coffee:2:26)
    at Object.<anonymous> (/home/vicentimartins/.atom/packages/git-plus/lib/git-plus.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:779:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "autocomplete-atom-api",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "emmet"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-html-entities, v0.1.0 (inactive)
autocomplete-python, v1.8.17 (inactive)
emmet, v2.4.3 (inactive)
git-plus, v5.27.0 (inactive)
language-blade, v0.26.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by akonwi** [comment]
@vicentimartins I think apm messed up the package update. go to the package directory and run `apm install`

**Comment by vicentimartins** [comment]
It's work now! Thnx @akonwi !

**Comment by akonwi** [comment]
@PsySc0rpi0n you might have the same problem as #768. Your version of atom is incompatible. You should update to the latest version of atom or downgrade git-plus
