### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by djdesign** [akonwi/git-plus#180]
[Enter steps to reproduce below:]
1. Ran update, opened up project and started working. Froze Atom.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.13
### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Users/DJ/.atom/packages/git-plus/lib/git.coffee:29

RangeError: Invalid string length
  at stdout (/Users/DJ/.atom/packages/git-plus/lib/git.coffee:24:8)
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:137:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```
### Commands

```
     -6:14.9 project-manager:toggle (atom-text-editor.editor)
  4x -6:14.0 core:move-down (atom-text-editor.editor.mini)
     -6:13.2 core:confirm (atom-text-editor.editor.mini)
     -6:02.9 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-light-ui)
     -5:59.8 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-light-ui)
     -0:23.8 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:18.6 command-palette:toggle (atom-text-editor.editor)
     -0:16.2 core:confirm (atom-text-editor.editor.mini)
     -0:16.1 git-plus:log (atom-text-editor.editor)
     -0:14.3 core:move-down (atom-text-editor.editor.mini)
     -0:11.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:11.0 core:cancel (atom-text-editor.editor.mini)
     -0:07.4 command-palette:toggle (atom-text-editor.editor)
     -0:06.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:06.5 core:cancel (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2
Search, v0.4.0
atom-terminal, vundefined
atomatigit, v1.2.3
browser-refresh, v0.8.3
color-picker, v1.6.0
command-logger, v0.23.0
css-comb, v2.0.3
editor-stats, v0.17.0
emmet, v2.3.7
git-plus, v4.4.13
language-htaccess, v0.1.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.12
linter-phpmd, v0.0.10
meteor-api, v2.12.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
php-getters-setters, v0.3.0
pretty-json, v0.3.2
project-colorize, v0.1.0
project-manager, v1.15.5
project-palette-finder, v2.4.16
remote-atom, v1.2.0
remote-edit, v1.7.2
remote-sync, v2.4.1
silent-sync, v1.1.5
ssh-config, v0.10.0
svg-preview, v0.5.1
terminal, v0.28.0
webbox-color, v0.5.6
wordpress, v0.2.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by akonwi** [comment]
I can't understand what the problem is. Have you been able to reproduce this?

**Comment by valilenk** [comment]
The problem still exists.

**Comment by akonwi** [comment]
@valilenk which command do you run to reproduce this error?
