### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by heroqu** [akonwi/git-plus#197]
[Enter steps to reproduce below:]

1. Menu -> Packages -> Git Plus -> "Add All"
2. Menu -> Packages -> Git Plus -> "Add All Commit Push"

**Atom Version**: 0.205.0
**System**: Mac OS X 10.9.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/one/.atom/packages/git-plus/lib/git.coffee:96

TypeError: Cannot read property 'path' of null
  at /Users/one/.atom/packages/git-plus/lib/git.coffee:96:10
  at Array.filter (native)
  at Object.gitRefreshIndex [as refresh] (/Users/one/.atom/packages/git-plus/lib/git.coffee:95:8)
  at git.cmd.stdout (/Users/one/.atom/packages/git-plus/lib/models/git-commit.coffee:107:13)
  at exit (/Users/one/.atom/packages/git-plus/lib/git.coffee:27:7)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  3x -2:14.4.0 core:close (atom-text-editor.editor.is-focused)
     -2:07.1.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -2:05.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:05.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:50.2.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -1:48 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:48 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:47.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:47.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:41.3.0 git-plus:log (atom-text-editor.editor.is-focused)
  2x -1:23.3.0 git-plus:diff (div.git-plus-log.native-key-bindings)
     -0:54.2.0 git-plus:log (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:41 git-plus:add-all (div.git-plus-log.native-key-bindings)
     -0:28.1.0 git-plus:add-all-commit-and-push (div.git-plus-log.native-key-bindings)
     -0:16.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "heroqu-seti"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter",
      "haskell-ghc-mod",
      "ide-haskell",
      "language-haskell",
      "autocomplete-haskell",
      "webbox-color"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.9
atom-runner, v2.4.1
color-picker, v2.0.4
git-plus, v5.0.4
heroqu-seti, v0.7.0
linter-jshint, v0.1.5
minimap, v4.9.2
seti-ui, v0.7.1
term2, v0.9.8

# Dev
No dev packages
```

**Comment by shingonoide** [comment]
:+1: but using linux version.
I using multi folders with TreeView.

**Comment by iDev0urer** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png) Same thing also on Mac OS X
