### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by elemenofi** [akonwi/git-plus#216]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.2.1

### Stack Trace

Failed to activate the git-plus package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\manuel.aberg@globant.com\AppData\Local\atom\app-0.204.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/manuel.aberg@globant.com/.atom/packages/git-plus/lib/views/repo-list-view.coffee:6:10)
    at Object.<anonymous> (/C:/Users/manuel.aberg@globant.com/.atom/packages/git-plus/lib/views/repo-list-view.coffee:87:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\manuel.aberg@globant.com\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:10.7.0 command-palette:toggle (atom-pane.pane.active)
     -0:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 git-plus:add (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "elemenofi-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
elemenofi-syntax, v0.0.0
git-plus, v5.2.1
jshint, v1.3.7

# Dev
No dev packages
```

**Comment by akonwi** [comment]
make sure you run `apm install` in the package directory or run `Update package dependencies` in the command palette
