### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by f3l1x** [akonwi/git-plus#220]
[Enter steps to reproduce below:]
1. Show log history
2. CTRL + W
3. That's all

**Atom Version**: 1.0.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At E:\Programs\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
  at E:\Programs\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (E:\Programs\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
  at tabs-tab.module.exports.TabView.destroy (E:\Programs\Atom\resources\app.asar\node_modules\tabs\lib\tab-view.js:194:14)
  at TabBarView.module.exports.TabBarView.removeTabForItem (E:\Programs\Atom\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:364:15)
  at E:\Programs\Atom\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:174:24
  at Emitter.module.exports.Emitter.emit (E:\Programs\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (E:\Programs\Atom\resources\app.asar\src\pane.js:379:20)
  at Pane.module.exports.Pane.destroyItem (E:\Programs\Atom\resources\app.asar\src\pane.js:442:16)
  at Pane.module.exports.Pane.destroyActiveItem (E:\Programs\Atom\resources\app.asar\src\pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (E:\Programs\Atom\resources\app.asar\src\workspace.js:600:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (E:\Programs\Atom\resources\app.asar\src\workspace.js:639:21)
  at atom-workspace.atom.commands.add.core:close (E:\Programs\Atom\resources\app.asar\src\workspace-element.js:308:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (E:\Programs\Atom\resources\app.asar\src\command-registry.js:241:29)
  at E:\Programs\Atom\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (E:\Programs\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (E:\Programs\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (E:\Programs\Atom\resources\app.asar\src\window-event-handler.js:180:20)

```
### Commands

```
  2x -1:31.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:26.2.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -1:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:23.7.0 settings-view:open (atom-text-editor.editor)
     -1:07.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:06.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:06.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:00.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:58.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:58.9.0 git-log:show (atom-text-editor.editor)
     -0:57.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:close (div.git-log)
     -0:19.4.0 core:cancel (a.stack-toggle)
  3x -0:18.4.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:08.7.0 core:cancel (ul.list-inline.tab-bar.inset-panel)
  2x -0:05.1.0 core:close (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "git-plus": {}
}
```
### Installed Packages

``` coffee
# User
git-log, v0.4.1
git-plus, v5.2.2
minimap, v4.10.1
pigments, v0.8.1

# Dev
No dev packages
```

**Comment by akonwi** [comment]
From the stack trace, this doesn't seem to be an issue with the package but a bug with the TabBarView package. 

Is this still a problem?
