### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'On branch masterYour branch is up-to-da...

### ISSUE THREAD

**Issue by jeremyf** [akonwi/git-plus#253]
[Enter steps to reproduce below:]
1. I staged, via the command line `git add .`, several files
2. I went into Atom and triggered "Git Plus: Commit"
   - I had just updated git-plus via the autoupdate. I did not reload Atom once the updates were completed. **If I reload Atom after the updates, the error does not show up**.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.9.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.3.3
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

```
modified:   app/models/identifier/unverified.rb
modified:   app/models/identifier/verified.rb
modified:   spec/models/identifier/unverified_spec.rb
modified:   spec/models/identifier/verified/group_spec.rb
modified:   spec/models/identifier/verified/netid_spec.rb
modified:   spec/models/identifier/verified_spec.rb'
```

```
At fs.js:519

Error: ENOENT: no such file or directory, open 'On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    modified:   app/models/identifier/unverified.rb
    modified:   app/models/identifier/verified.rb
    modified:   spec/models/identifier/unverified_spec.rb
    modified:   spec/models/identifier/verified/group_spec.rb
    modified:   spec/models/identifier/verified/netid_spec.rb
    modified:   spec/models/identifier/verified_spec.rb'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at git.cmd.stdout (/Users/jfriesen/.atom/packages/git-plus/lib/models/git-commit.coffee:76:69)
  at exit (/Users/jfriesen/.atom/packages/git-plus/lib/git.coffee:27:7)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -1:17.4.0 sublime-word-navigation:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:16.7.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:16.1.0 core:cut (atom-text-editor.editor.is-focused)
     -1:15.8.0 core:delete (atom-text-editor.editor.is-focused)
     -1:15.4.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:14.8.0 core:paste (atom-text-editor.editor.is-focused)
     -1:14 core:backspace (atom-text-editor.editor.is-focused)
     -1:13.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:09.3.0 sublime-word-navigation:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -1:09.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:08.0 core:cut (atom-text-editor.editor.is-focused)
     -1:07.4.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:06.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.4.0 git-plus:commit (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "ruby-blue-syntax"
    ],
    "disabledPackages": [
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml",
      "language-java",
      "language-csharp",
      "language-clojure",
      "language-c",
      "keybinding-resolver",
      "project-ring",
      "sourcegraph-atom",
      "go-to-spec",
      "autocomplete-ruby",
      "multi-cursor-plus",
      "linter-rubocop",
      "git-blame-plus",
      "chary-tree-view",
      "tree-view-git-modified",
      "symbols-view",
      "minimap",
      "block-cursor",
      "linter-ruby"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "tags",
      ".tag*"
    ]
  },
  "git-plus": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.10
atom-ctags, v4.1.4
atom-pair, v2.0.5
atom-text-transformer, v0.7.0
autocomplete-ctags, v0.3.1
color-picker, v2.0.11
file-icons, v1.6.3
git-log, v0.4.1
git-plus, v5.3.3
highlight-line, v0.11.0
indent-guide-improved, v1.4.1
jsonlint, v1.1.2
keyboard-scroll, v0.4.0
language-diff, v0.3.0
language-dot, v1.6.0
language-haml, v0.21.0
language-rspec, v0.3.0
language-ruby, v0.57.0
language-rust, v0.4.4
linter, v1.3.4
linter-rust, v0.2.6
pigments, v0.9.3
project-manager, v1.15.11
racer, v0.16.0
rails-rspec, v0.3.2
ruby-block, v0.3.5
ruby-blue-syntax, v0.1.13
rust-api-docs-helper, v0.5.1
sublime-word-navigation, v0.1.2
terminal-status, v1.6.8
the-closer, v0.5.0
trailing-spaces, v0.3.2
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by akonwi** [comment]
I apologize for not responding to this. Is it still an issue? I'm marking as stale and closing it. We can re-open it if its a problem
