### ISSUE TITLE
Uncaught TypeError: directions[splitDir] is not a function

### ISSUE THREAD

**Issue by lolitaloco** [akonwi/git-plus#296]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: linux 4.1.8-1-lts
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.4.7

### Stack Trace

Uncaught TypeError: directions[splitDir] is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/q/q.js:128

TypeError: directions[splitDir] is not a function
    at GitCommit.module.exports.GitCommit.splitPane (/home/anna/.atom/packages/git-plus/lib/models/git-commit.coffee:121:5)
    at /home/anna/.atom/packages/git-plus/lib/models/git-commit.coffee:93:12
    at _fulfilled (/usr/share/atom/resources/app.asar/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/usr/share/atom/resources/app.asar/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/usr/share/atom/resources/app.asar/node_modules/q/q.js:756:13)
    at /usr/share/atom/resources/app.asar/node_modules/q/q.js:564:44
    at flush (/usr/share/atom/resources/app.asar/node_modules/q/q.js:110:17)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

### Commands

```
     -0:13.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:07.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.0 git-plus:add-and-commit (atom-text-editor.editor)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/anna/Projects",
    "themes": [
      "one-light-ui",
      "one-dark-vivid-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "block-comment"
    ],
    "disabledPackages": [
      "my-package",
      "project-sidebar",
      "autocomplete-php"
    ]
  },
  "git-plus": {
    "splitPane": "bottom"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.0
aligner-php, v1.0.0
docblockr, v0.7.3
file-icons, v1.6.9
git-plus, v5.4.7
jquery-snippets, v11.0.0
linter, v1.7.2
linter-jscs, v3.0.0
linter-phpcs, v1.1.4
minimap, v4.13.4
one-dark-vivid-syntax, v1.1.1
project-manager, v2.6.1
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by akonwi** [comment]
Make sure in the settings, your direction is set to 'up', 'down', 'left', or 'right'

**Comment by lolitaloco** [comment]
Thank you, that seems to have fixed my problems. (Don't know where I got 'bottom' from, I'll blame it on temporary insanity. :neckbeard: )
