### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by RadianSmile** [akonwi/git-plus#309]
[Enter steps to reproduce below:]

1. cmd-shift-h
2. log  and enter
then show the following bug.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.4.7

### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Volumes/HDD/Users/Radian/.atom/packages/git-plus/lib/models/git-log.coffee:14

TypeError: atom.workspace.open(...).done is not a function
  at gitLog (/Volumes/HDD/Users/Radian/.atom/packages/git-plus/lib/models/git-log.coffee:14:35)
  at /Volumes/HDD/Users/Radian/.atom/packages/git-plus/lib/git-plus-commands.coffee:44:48
  at GitPaletteView.module.exports.GitPaletteView.confirmed (/Volumes/HDD/Users/Radian/.atom/packages/git-plus/lib/views/git-palette-view.coffee:87:5)
  at GitPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -2:07.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:05.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:03.0 core:close (atom-text-editor.editor.is-focused)
     -1:33.3.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -1:32.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:30.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:28.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:27.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:27.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:27.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:24.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:24.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:23.7.0 core:close (atom-text-editor.editor.is-focused)
     -0:04.9.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "processing-language",
      "processing-language",
      "processing-language",
      "processing-language",
      "copy-as-rtf",
      "preview",
      "processing",
      "symbols-view"
    ],
    "ignoredNames": [
      "*.pde",
      ".git/*",
      "*.map",
      "*.min.js",
      "*.DS_Store",
      "/_notes"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.16
atom-ctags, v4.4.0
atom-jade, v0.3.0
autocomplete-paths, v1.0.2
clipboard-history, v0.6.6
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
git-plus, v5.4.7
linter, v1.10.0
linter-jshint, v1.2.1
project-manager, v2.6.5
react, v0.12.10
recent-projects, v0.9.5
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by akonwi** [comment]
You shouldn't see this error anymore in the latest update. Can you confirm that?
