### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by chamunks** [akonwi/git-plus#311]
[Enter steps to reproduce below:]

1. Open Git-plus Menu
2. Other than that I don't know what I did.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'contains' of undefined

```
At /Users/chamunks/.atom/packages/git-plus/lib/git-plus.coffee:148

TypeError: Cannot read property 'contains' of undefined
  at /Users/chamunks/.atom/packages/git-plus/lib/git-plus.coffee:148:24
  at Array.some (native)
  at Object.module.exports.setupBranchesMenuToggle (/Users/chamunks/.atom/packages/git-plus/lib/git-plus.coffee:147:31)
  at Object.module.exports.consumeStatusBar (/Users/chamunks/.atom/packages/git-plus/lib/git-plus.coffee:131:6)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -1:12.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
  8x -0:13.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:02.9.0 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "tidy-markdown"
    ]
  }
}
```

### Installed Packages

```coffee
# User
about, v1.1.0
auto-update-packages-1, v1.0.0
git-go, v1.0.1
git-plus, v5.5.0
git-tab-status, v1.7.0
jekyll-new-post, v0.1.2
json-colorer, v0.3.0
language-docker, v1.1.3
language-salt, v0.4.0
linter, v1.10.0
linter-javac, v1.3.0
markdown-preview-plus, v2.2.2
minimap, v4.16.0
pretty-json, v0.4.1
save-session, v0.15.7
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by akonwi** [comment]
Does this happen each time you open atom and start using the package?

**Comment by chamunks** [comment]
So far it happened this session with a freshly opened atom switching opening a file inside a git repo.

**Comment by akonwi** [comment]
Okay. If this happens again, let me know. I haven't been able to replicate it but I might have a fix

**Comment by alessandrotesoro** [comment]
Having the same issue. Yes it happens every time I open a new session/window in Atom.

Not sure if related, now I can't even push to any repository anymore ( haven't changed anything ).

**Comment by chamunks** [comment]
Thanks
