### ISSUE TITLE
Uncaught Error: Cannot find module 'flavored-path'

### ISSUE THREAD

**Issue by haoxilu** [akonwi/git-plus#321]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.5.7

### Stack Trace

Uncaught Error: Cannot find module 'flavored-path'

```
At module.js:336

Error: Cannot find module 'flavored-path'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\喜路\.atom\packages\git-plus\lib\git.coffee:2:8)
  at Object.<anonymous> (C:\Users\喜路\.atom\packages\git-plus\lib\git.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\喜路\.atom\packages\git-plus\lib\git-plus.coffee:3:7)
  at Object.<anonymous> (C:\Users\喜路\.atom\packages\git-plus\lib\git-plus.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at Package.module.exports.Package.activateConfig (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:250:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:215:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:158:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:170:21)
  at C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:301:17
  at Emitter.module.exports.Emitter.emit (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:664:27)
  at C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:26
  at exit (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\喜路\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
  2x -3:20.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by akonwi** [comment]
Make sure you run `apm install` within the package directory or from atom with the `update package dependencies` command

**Comment by haoxilu** [comment]
Thank you !
