### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of null

### ISSUE THREAD

**Issue by Strainyy** [akonwi/git-plus#324]
Commiting to BitBucket and I'm receiving an error...

Steps to reproduce:

1. Change a file
2. Select commit from the git-plus package menu
3. Enter a commit message
4. Select push from the git-plus package menu

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of null

```
At /Users/jamesstrain/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:244

TypeError: Cannot read property 'webkitMatchesSelector' of null
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/jamesstrain/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:244:26)
    at CommandRegistry.handleCommandEvent (/Users/jamesstrain/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/jamesstrain/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at HTMLDivElement.<anonymous> (/Users/jamesstrain/.atom/packages/git-plus/lib/git-plus.coffee:150:25)
    at HTMLDivElement.jQuery.event.dispatch (/Users/jamesstrain/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/jamesstrain/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:23 git-plus:add (atom-text-editor.editor.is-focused)
     -6:12.2.0 git-plus:rebase (atom-text-editor.editor.is-focused)
  5x -1:59.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:57.5.0 editor:newline (atom-text-editor.editor.is-focused)
 15x -1:44.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:37.4.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:35.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:35.6.0 editor:newline (atom-text-editor.editor.is-focused)
 27x -1:30.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:15.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:13.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:05.7.0 git-plus:commit (ul.list-inline.tab-bar.inset-panel)
  4x -0:47.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.5.0 git-plus:push (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
  2x -6:42.9.0 git-plus:checkout (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "audioBeep": false
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
git-plus, v5.6.1
linter, v1.11.1
linter-jshint, v1.2.1

# Dev
No dev packages
```

**Comment by akonwi** [comment]
This is really odd. This bit of code should only be triggered when the git branch part of the status-bar is clicked. Also, the root of that error is coming from inside atom's CommandRegistry class. 

Can you reproduce this? I'm unable to

**Comment by Strainy** [comment]
Just updating, this error is triggered when clicking the git branch part of the status-bar as indicated by akonwi. Could it have something to do with my git repo being private on BitBucket?

**Comment by akonwi** [comment]
It shouldn't because the command only pulls up local branches. I'll raise this with a pull request in the atom core repo
