### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by paradox460** [akonwi/git-plus#374]
**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.12.0

### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/jsandberg/.atom/packages/git-plus/lib/git.coffee:51:13
    at Object.module.exports.git.cmd (/Users/jsandberg/.atom/packages/git-plus/lib/git.coffee:48:9)
    at Object.module.exports.gitBranches (/Users/jsandberg/.atom/packages/git-plus/lib/models/git-branch.coffee:44:7)
    at /Users/jsandberg/.atom/packages/git-plus/lib/git-plus.coffee:96:123
```

### Commands

```
  5x -1:12.8.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.insert-mode)
     -0:07.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:06.9.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:03.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:02.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:00.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:00.3.0 git-plus:checkout (atom-text-editor.editor.vim-mode-plus.insert-mode)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "save-session",
      "emacs-flow",
      "autocomplete",
      "feedback",
      "deprecation-cop",
      "ruby-string-interpolation"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "highlight-line",
      "whitespace",
      "notifications"
    ],
    "themes": [
      "quantum-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by akonwi** [comment]
Check [this](https://github.com/wende/autocomplete-erlang/issues/7) out

**Comment by akonwi** [comment]
Since this is an issue beyond this package, I'm going to close it.
