### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by umputun** [akonwi/git-plus#382]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.12.0

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at GutterContainer.module.exports.GutterContainer.onDidAddGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:81:27)
    at TextEditor.module.exports.TextEditor.onDidAddGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:487:35)
    at TextEditorPresenter.module.exports.TextEditorPresenter.observeModel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:289:39)
    at new TextEditorPresenter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:45:12)
    at new TextEditorComponent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:107:24)
    at atom-text-editor.TextEditorElement.mountComponent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:213:24)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:92:14)
    at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:165:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:175:19)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:692:21)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:672:19)
    at showFile (/Users/umputun/.atom/packages/git-plus/lib/models/git-commit.coffee:68:5)
    at startCommit (/Users/umputun/.atom/packages/git-plus/lib/models/git-commit.coffee:76:5)
    at /Users/umputun/.atom/packages/git-plus/lib/models/git-commit.coffee:87:20
```

### Commands

```
     -2:37.3.0 core:copy (atom-text-editor.editor.is-focused)
     -2:33.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:30 core:save (atom-text-editor.editor.is-focused)
  4x -2:06.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:04.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:52.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:50.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:49.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:49.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:48.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:47.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:47.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:46.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:44.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 git-plus:add-all-commit-and-push (atom-text-editor.editor.is-focused)
  2x -0:05.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-darkula-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-mac-terminal",
      "atom-terminal",
      "file-type-icons",
      "config-import-export",
      "minimap",
      "git-blame",
      "autocomplete-go",
      "go-playground",
      "go-oracle",
      "linter-python-pep8",
      "terminal-plus",
      "terminal-panel",
      "method-separator"
    ],
    "themes": [
      "atom-dark-ui",
      "darkula-syntax"
    ]
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
atom-beautify, v0.28.21
atom-html-preview, v0.1.13
autoclose-html, v0.19.0
autocomplete-python, v1.5.1
build, v0.53.0
darkula-syntax, v0.3.0
environment, v1.1.1
file-icons, v1.6.14
git-hide, v0.1.2
git-log, v0.4.1
git-plus, v5.12.0
go-config, v0.3.3
go-find-references, v1.2.3
go-plus, v3.5.2
go-rename, v0.3.0
highlight-selected, v0.11.1
language-ansible, v0.1.3
language-docker, v1.1.6
language-nginx, v0.6.1
linter, v1.11.3
linter-golinter, v1.1.0
linter-pep8, v1.2.1
markdown-preview-plus, v2.2.2
markdown-writer, v2.2.0
minimap-git-diff, v4.1.8
open-recent, v4.0.1
open-terminal-here, v2.1.4
pretty-json, v0.4.1
project-manager, v2.7.5
python-tools, v0.6.7
remote-edit, v1.8.23
save-session, v0.15.7
synced-sidebar, v0.4.3
tab-switcher, v1.3.3
tabs-to-spaces, v1.0.1
terminal-status, v1.6.8
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by akonwi** [comment]
Are there steps to reproduce this?

**Comment by umputun** [comment]
no clue. It happened once, after atom's restart. I don't see it anymore.
