### ISSUE TITLE
Uncaught TypeError: _ref2.submoduleForPath is not a function

### ISSUE THREAD

**Issue by vladimir-plotvinov** [akonwi/git-plus#442]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.13.4
### Stack Trace

Uncaught TypeError: _ref2.submoduleForPath is not a function

```
At /opt/atom/resources/app.asar/src/pane.js:1002

TypeError: _ref2.submoduleForPath is not a function
    at /home/vp/.atom/packages/git-plus/lib/git.coffee:136:5
    at Array.filter (native)
    at Object.module.exports.git.getSubmodule (/home/vp/.atom/packages/git-plus/lib/git.coffee:136:5)
    at dir (/home/vp/.atom/packages/git-plus/lib/models/git-commit.coffee:13:8)
    at /home/vp/.atom/packages/git-plus/lib/models/git-commit.coffee:79:16
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/opt/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/opt/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/opt/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/opt/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:59 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:58.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:56.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:55.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:48.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42.1.0 core:save (atom-text-editor.editor.is-focused)
 15x -0:36.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:22.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:18.2.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:16.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:13.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:10.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "jquery-snippets",
      "git-diff-details",
      "atom-hg",
      "hg-commit"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v3.0.0
atom-jade, v0.3.0
css-color-underline, v1.0.1
git-plus, v5.13.4
html-id-class-snippets, v1.4.1
jade-autocompile, v0.8.3
language-antlers, v0.3.4
language-blade, v0.25.2

# Dev
No dev packages
```

**Comment by jbree** [comment]
Also seeing this issue whenever I try to commit using git-plus. Any ideas?

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 14.04.4
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.15.0


### Stack Trace

Uncaught TypeError: _ref2.submoduleForPath is not a function

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

TypeError: _ref2.submoduleForPath is not a function
    at /home/jbreeden/.atom/packages/git-plus/lib/git.coffee:135:5
    at Array.filter (native)
    at Object.module.exports.git.getSubmodule (/home/jbreeden/.atom/packages/git-plus/lib/git.coffee:135:5)
    at dir (/home/jbreeden/.atom/packages/git-plus/lib/models/git-commit.coffee:13:8)
    at /home/jbreeden/.atom/packages/git-plus/lib/models/git-commit.coffee:79:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:14.2.0 build:select-active-target (atom-text-editor.editor.is-focused)
  4x -1:13.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:13 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.1.0 build:select-active-target (atom-text-editor.editor.is-focused)
  3x -1:08.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:06.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.4.0 git-plus:menu (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.8.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.3.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:20.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.1.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:16.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.cpp": [
        "h"
      ]
    },
    "disabledPackages": [
      "spell-check",
      "atom-ctags",
      "atom-gdb",
      "atom-easy-jsdoc",
      "activate-power-mode"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
build, v0.64.0
busy, v0.5.0
docblockr, v0.7.3
file-icons, v1.7.14
fonts, v1.5.0
git-diff-details, v1.3.0
git-plus, v5.15.0
language-cmake, v0.1.4
language-doxygen, v0.2.1
linter, v1.11.10
linter-clang, v3.4.4
linter-jsonlint, v1.2.5
minimap, v4.24.6
minimap-git-diff, v4.3.1
pigments, v0.29.2
pretty-json, v1.4.1
slickedit-select, v1.6.0
svn, v0.0.11
symbol-gen, v1.3.1
symbols-tree-view, v0.13.2

# Dev
No dev packages
```

**Comment by vladimir-plotvinov** [comment]
Hi, I think it's because of the package "git-diff-details". I have it this
package too. I deleted it and the problem is gone

ср, 15 июн. 2016 г. в 18:01, Joshua <notifications@github.com>:

**Comment by choppedpork** [comment]
[Enter steps to reproduce below:]

1. ctrl-shift-h
2. commit
3. enter commit message
4. ctrl-s
5. sad face :(

note - no `git-diff-details` in my installation.

**Atom Version**: 1.8.0
**System**: Debian GNU/Linux
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.16.2


### Stack Trace

Uncaught TypeError: _ref2.submoduleForPath is not a function

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

TypeError: _ref2.submoduleForPath is not a function
    at /home/solid/.atom/packages/git-plus/lib/git.coffee:135:5
    at Array.filter (native)
    at Object.module.exports.git.getSubmodule (/home/solid/.atom/packages/git-plus/lib/git.coffee:135:5)
    at dir (/home/solid/.atom/packages/git-plus/lib/models/git-commit.coffee:15:8)
    at /home/solid/.atom/packages/git-plus/lib/models/git-commit.coffee:108:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:00.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:49.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:45.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -4:42.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:31.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:11.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:23.4.0 git-plus:checkout (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.9.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:14.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:14.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.1.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 11x -0:05.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "symbols-view",
      "atom-ctags"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "git-plus": {
    "splitPane": "Right"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.1.0
builder-go, v1.0.0
git-plus, v5.16.2
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-ansible, v0.1.11
language-docker, v1.1.6
language-groovy, v0.6.0
language-hcl, v0.4.0
language-terraform, v0.7.4
linter, v1.11.14
linter-ansible-linting, v1.2.0
linter-ansible-syntax, v1.1.0
navigator-godef, v1.0.3
svn, v0.0.12
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by choppedpork** [comment]
...and less than 5 minutes later I've discovered what the issue is - the `svn` plugin!

**Comment by Yajo** [comment]
I'm getting this all the time... Could you link to the issue there please?

**Comment by choppedpork** [comment]
@Yajo I've had to uninstall the `svn` plugin to get this to work. I have not raised an issue on the svn plugin side.

**Comment by akonwi** [comment]
I'm not sure what's going on here. @choppedpork for you it could have been that the svn plugin was returning instances of svn repositories when it should not have been and that's why this error is happening. I've installed the svn package and I can't replicate this problem.

For the other packages like git-diff-details, I have no hypothesis. 

Can anyone confirm that this still occurs?

**Comment by choppedpork** [comment]
I've not had this happen myself since disabling the `svn` plugin.

**Comment by akonwi** [comment]
I found the cause of this and fixed it with the latest release. See #548
