### ISSUE TITLE
Failed to activate

### ISSUE THREAD

**Issue by pdxwolfy** [akonwi/git-plus#465]
[Enter steps to reproduce below:]
1. Start Atom
2. Make edit
3. Press Cmd-A-P
4. Error is thrown
5. Commit not written

This started this morning; I made successful commit/pushes yesterday.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.15.0
### Stack Trace

Failed to activate the git-plus package

```
At Cannot find module './models/git-open-changed-files'

Error: Cannot find module './models/git-open-changed-files'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/git-plus/lib/git-plus.coffee:39:26)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/git-plus/lib/git-plus.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:09.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.1.0 git-plus:add-all-commit-and-push (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "about",
      "autocomplete-atom-api",
      "autoflow",
      "autosave",
      "background-tips",
      "metrics",
      "timecop",
      "welcome",
      "wrap-guide",
      "archive-view",
      "symbols-view",
      "tree-view-open-files",
      "tree-view-git-branch",
      "linter-tidy",
      "language-gfm",
      "markdown-preview"
    ],
    "ignoredNames": [
      "*.a",
      "*.bak",
      "*.class",
      "*.db",
      "*.dds",
      "*.dll",
      "*.dylib",
      "*.eot",
      "*.exe",
      "*.gif",
      "*.ico",
      "*.idb",
      "*.jar",
      "*.jpeg",
      "*.jpg",
      "*.lib",
      "*.ncb",
      "*.o",
      "*.obj",
      "*.pdb",
      "*.pdf",
      "*.png",
      "*.psd",
      "*.pyc",
      "*.pyo",
      "*.sdf",
      "*.so",
      "*.sublime-workspace",
      "*.suo",
      "*.swf",
      "*.tga",
      "*.ttf",
      "*.zip",
      "*~",
      ".DS_Store",
      ".git"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "advanced-open-file"
    ],
    "projectHome": "/Users/wolfy/Atom"
  },
  "git-plus": {
    "splitPane": "Down"
  }
}
```
### Installed Packages

``` coffee
# User
atom-sync, v0.7.3
autoclose-html, v0.23.0
chary-tree-view, v0.2.3
file-types, v0.5.1
git-plus, v5.15.0
incsearch, v0.3.3
language-markdown, v0.14.0
language-mason, v2.0.4
less-than-slash, v0.13.0
linter, v1.11.8
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-htmlhint, v1.1.4
linter-js-standard, v3.3.3
linter-jshint, v2.1.0
linter-lesshint, v1.5.0
linter-markdown, v1.5.2
linter-perl-check-syntax, v0.3.0
linter-perlcritic, v0.3.3
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-ruby-reek, v1.5.1
markdown-preview-plus, v2.4.0
merge-conflicts, v1.4.4
multi-wrap-guide, v0.24.0
omni-ruler, v0.4.2
open-in-browsers, v0.0.16
ruby-block, v0.3.5
run-in-browser, v0.1.3
tab-control, v0.6.9
tab-smart-sort, v0.1.4

# Dev
No dev packages
```

**Comment by saidmoya12** [comment]
Check the app permissions or test with sudo / run as adminisrtator atom

**Comment by pdxwolfy** [comment]
I couldn't find any app permission problems. I had to use apm to uninstall and reinstall. Seems to be working now.

**Comment by pdxwolfy** [comment]
I think this can be closed if you want to.
