### ISSUE TITLE
Updated git-plus fails to load

### ISSUE THREAD

**Issue by capouch** [akonwi/git-plus#522]
I hope this can be fixed quickly.  I use git intensively in Atom, and of course now I wish I wouldn't have hit the upgrade button.

It's looking for a package, apparently, that doesn't exist:

[Enter steps to reproduce below:]
1. Respond to prompt to upgrade git-plus
2. Suffer as upgraded package now won't load

**Atom Version**: 1.12.0-dev-2486a12
**Electron Version**: 1.3.6
**System**: linux 4.1.13
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.18.0
### Stack Trace

Failed to load the git-plus package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/usr/local/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/local/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Object.<anonymous> (/home/brianc/.atom/packages/git-plus/lib/git-plus.coffee:2:7)
    at Object.<anonymous> (/home/brianc/.atom/packages/git-plus/lib/git-plus.coffee:1:1)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Package.module.exports.Package.requireMainModule (/usr/local/share/atom/resources/app.asar/src/package.js:741:27)
    at /usr/local/share/atom/resources/app.asar/src/package.js:118:28
    at Package.module.exports.Package.measure (/usr/local/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/local/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/local/share/atom/resources/app.asar/src/package-manager.js:455:14)
    at /usr/local/share/atom/resources/app.asar/src/package-manager.js:400:19
    at Config.module.exports.Config.transact (/usr/local/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/local/share/atom/resources/app.asar/src/package-manager.js:395:19)
    at /usr/local/share/atom/resources/app.asar/src/atom-environment.js:768:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter",
      "autocomplete-atom-api"
    ],
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
git-plus, v5.18.0 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v7.3.2 (inactive)
react, v0.16.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.1 (inactive)
one-light-ui, v1.6.1 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.4 (inactive)
solarized-light-syntax, v1.0.4 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.3 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.7 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.0 (inactive)
snippets, v1.0.3 (inactive)
spell-check, v0.68.3 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.53.2 (inactive)
language-clojure, v0.22.0 (inactive)
language-coffee-script, v0.47.3 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.0 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.46.0 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.121.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.1 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.11 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by akonwi** [comment]
There's an error with the way the atom is updating the package it seems. The package dependencies should be installed as part of the update. Even if they weren't, `atom-space-pen-views` has been a dependency since one of the first releases so there shouldn't be a need to re-install it. 

The immediate solution I can think of is to do:
`cd ~/.atom/packages/git-plus && apm install`.

Alternatively you can use the `Update Package Dependencies: Update` command from atom's command palette.

**Comment by simenbrekken** [comment]
Just wanted to chime in and confirm that `cd ~/.atom/packages/git-plus && apm install.` works for me (OSX Sierra) but `Update Package Dependencies: Update` did nothing.

**Comment by akonwi** [comment]
Thanks @simenbrekken. I've updated my comment to reflect that

**Comment by evmin** [comment]
Just tried

> cd ~/.atom/packages/git-plus && apm install

No luck. Same problem (with v 7.0 though - previous versions worked correctly.)

**Comment by akonwi** [comment]
@evmin v7.0.3 should fix it for you

**Comment by cbcoutinho** [comment]
I'm having the same error on git-plus v7.0.5, same as this error and #580 

Should I downgrade to v7.0.3?

**Comment by akonwi** [comment]
@cbcoutinho did you do `cd ~/.atom/packages/git-plus && apm install`?

**Comment by cbcoutinho** [comment]
No, I just installed git-plus using the settings menu in Atom. Why would I do that?

Just updated to 1.12.9 and having the same problem as in 1.12.7

**Comment by akonwi** [comment]
@cbcoutinho Sorry, `cd ~/.atom/packages/git-plus && apm install` is what you need to do to fix this.

For some reason during updating, the 'atom-space-pen-views' dependency gets lost sometimes. Running `apm install` will download the dependencies again
