### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by vincentLabbe** [akonwi/git-plus#620]
[Enter steps to reproduce:]

1. Open the git pull command prompt 
2. Try to pull from a branch

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/vincent.labbe/.atom/packages/git-plus/lib/models/_pull.coffee:9

TypeError: Cannot read property '0' of undefined
    at getUpstream (/packages/git-plus/lib/models/_pull.coffee:9:23)
    at module.exports (/packages/git-plus/lib/models/_pull.coffee:17:44)
    at module.exports (/packages/git-plus/lib/models/git-pull.coffee:12:5)
    at /packages/git-plus/lib/git-plus-commands.coffee:73:50
    at GitPaletteView.module.exports.GitPaletteView.confirmed (/packages/git-plus/lib/views/git-palette-view.coffee:90:5)
    at GitPaletteView.module.exports.SelectListView.confirmSelection (/packages/git-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /packages/git-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:09.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:13.3.0 git-plus:menu (atom-pane.pane.active)
     -0:10.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 1.3.9 
auto-update-packages 1.0.1 
autocomplete-modules 1.6.7 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.15 
git-plus 7.2.2 
merge-conflicts 1.4.4 
pigments 0.39.0 
platformio-ide-terminal 2.2.2 
```

**Comment by akonwi** [comment]
What is the name of the branch you are trying to pull from?

**Comment by vincentLabbe** [comment]
develop, but I updated Atom and the problem doesn't seem to occur anymore, i'll test it more thoroughly
