### ISSUE TITLE
Uncaught TypeError: gp.deactivate is not a function

### ISSUE THREAD

**Issue by cenap** [akonwi/git-plus#626]
Just adding a new project folder I get this error:

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.3.0

### Stack Trace

Uncaught TypeError: gp.deactivate is not a function

```
At /home/salih/.atom/packages/git-plus/lib/git-plus.coffee:88

TypeError: gp.deactivate is not a function
    at onPathsChanged (/packages/git-plus/lib/git-plus.coffee:88:6)
    at /packages/git-plus/lib/git-plus.coffee:108:48
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:277:29)
    at /app.asar/src/atom-environment.js:1013:40
    at /app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -6:42.2.0 settings-view:install-packages-and-themes (input.hidden-input)
     -6:35.9.0 core:confirm (input.hidden-input)
     -3:47.1.0 command-palette:toggle (input.hidden-input)
     -3:25.5.0 git-plus:init (input.hidden-input)
     -2:16.8.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:08.1.0 git-plus:init (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -1:19.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
git-plus 7.3.0 
linter 1.11.23 
linter-csslint 1.3.3 
linter-eslint 8.1.2 
linter-jshint 3.0.2 
minimap 4.26.8 
Remote-FTP 0.10.5 
```

**Comment by akonwi** [comment]
There will be a fix for this in the next release
