### ISSUE TITLE
Crash when icon clicked after todays update.

### ISSUE THREAD

**Issue by mharding7va** [akonwi/git-plus#629]
Immediate crash when the git icon is clicked
![screen shot 2017-02-20 at 6 22 25 pm](https://cloud.githubusercontent.com/assets/8609447/23145037/a5f84160-f799-11e6-8a84-360b1b57f7fa.png)

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.3.0

### Stack Trace

Uncaught Error: Cannot find module './models/git-delete-local-branch'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:379

Error: Cannot find module './models/git-delete-local-branch'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at getCommands (/packages/git-plus/lib/git-plus-commands.coffee:5:28)
    at GitPaletteView.module.exports.GitPaletteView.show (/packages/git-plus/lib/views/git-palette-view.coffee:37:5)
    at GitPaletteView.module.exports.GitPaletteView.toggle (/packages/git-plus/lib/views/git-palette-view.coffee:24:8)
    at GitPaletteView.module.exports.GitPaletteView.initialize (/packages/git-plus/lib/views/git-palette-view.coffee:13:6)
    at /packages/git-plus/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/git-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
    at /packages/git-plus/lib/views/git-palette-view.coffee:8:7)
    at /packages/git-plus/lib/git-plus.coffee:108:37)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:105:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:69:7)
```

### Commands

```
     -0:47.5.0 core:backspace (input.hidden-input)
     -0:46.3.0 core:move-down (input.hidden-input)
  2x -0:45.3.0 core:backspace (input.hidden-input)
     -0:41.2.0 core:save (input.hidden-input)
     -0:36.5.0 git-plus:menu (ul.list-inline.tab-bar.inset-panel)
     -0:30.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cobalt2-syntax.theme-atom-dark-ui)
  2x -0:21.4.0 git-plus:menu (div.panels-item)
```

### Non-Core Packages

```
astromac-ui 0.1.0 
atom-bootstrap3 1.2.12 
atom-monokai 0.10.9 
atom-runner 2.7.1 
atom-terminal 0.8.0 
atom-visual-studio-code-ui 1.3.4 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
cobalt2-syntax 0.5.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.15 
flex-tool-bar 0.11.0 
git-plus 7.3.0 
highlight-line 0.12.0 
highlight-selected 0.12.0 
imdone-atom 2.1.18 
language-mongodb 0.3.1 
linter 1.11.23 
linter-jshint 3.0.2 
minimap 4.26.8 
monokai 0.22.0 
monokai-seti 0.7.0 
native-ui 0.20.4 
open-recent 5.0.0 
php-cs-fixer 4.1.0 
php-debug 0.2.4 
pigments 0.39.0 
pretty-json 1.6.1 
project-manager 3.3.3 
project-sidebar 1.3.0 
recent-projects 0.13.1 
Remote-FTP 0.10.5 
seti-ui 1.6.1 
simple-drag-drop-text 0.3.4 
todo-show 1.11.0 
tool-bar 1.0.1 
```

**Comment by akonwi** [comment]
It seems like you don't have the latest version of the package installed. v7.3.1 is the latest and you have v7.3.0
