### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rlam3** [akonwi/git-plus#630]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.3.1

### Stack Trace

Failed to load the git-plus package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/git-plus/lib/git-plus.coffee:2:26)
    at /packages/git-plus/lib/git-plus.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
     -6:30.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.theme-monokai.theme-seti-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-django 0.3.2 
atom-html-preview 0.1.22 
atom-jinja2 0.6.0 
autocomplete-modules 1.6.7 
autocomplete-python 1.8.54 
autocomplete-swift 1.0.3 
autoupdate-packages 1.3.1 
color-picker 2.2.5 
dash 1.7.0 
emmet 2.4.3 
file-icons 2.0.15 
git-plus 7.3.1 
javascript-snippets 1.2.1 
kite 0.10.2 
language-emberscript 0.1.0 
language-ini 1.18.0 
language-nginx 0.6.2 
language-restructuredtext 1.0.2 
language-sphinx 0.1.6 
language-stylus 0.2.0 
language-swift 0.5.0 
linter 1.11.23 
linter-jshint 3.0.2 
linter-pycodestyle 2.0.0 
linter-sourcekitten-syntax 0.1.1 
linter-swiftc 2.0.0 
markdown-preview-plus 2.4.3 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-git-diff 4.3.1 
monokai 0.22.0 
pigments 0.39.0 
platformio-ide-terminal 2.2.3 
pretty-json 1.6.1 
python-autopep8 0.1.3 
python-tools 0.6.9 
react 0.16.2 
rst-preview-pandoc 0.1.12 
script 3.14.1 
set-syntax 0.3.2 
seti-ui 1.6.1 
sort-lines 0.14.0 
ssh-config 0.10.1 
Stylus 3.1.0 
swift-debugger 0.1.2 
sync-settings 0.8.1 
synced-sidebar 0.4.3 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
turbo-javascript 1.4.0 
vim-mode 0.66.0 
Zen 0.16.4 
```

**Comment by akonwi** [comment]
run `apm install` from the package directory
