### ISSUE TITLE
Uncaught TypeError: this.element.getModel is not a function

### ISSUE THREAD

**Issue by robhicks** [akonwi/git-plus#650]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta0 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.12.4
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.4.0

### Stack Trace

Uncaught TypeError: this.element.getModel is not a function

```
At /Users/robhicks/.atom/packages/git-plus/node_modules/atom-space-pen-views/lib/text-editor-view.js:40

TypeError: this.element.getModel is not a function
    at /packages/git-plus/node_modules/atom-space-pen-views/lib/text-editor-view.js:40:34)
    at Object.content (/packages/git-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:26:45)
    at Builder.tag (/packages/git-plus/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/git-plus/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.SelectListView.content (/packages/git-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:22:19)
    at /packages/git-plus/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/git-plus/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/git-plus/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/git-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
    at /packages/git-plus/lib/views/git-palette-view.coffee:8:7)
    at /packages/git-plus/lib/git-plus.coffee:113:86)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:15.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.use-animations)
     -0:10.7.0 git-plus:menu (atom-pane.pane)
```

### Non-Core Packages

```
aligner 0.22.3 
aligner-stylus 1.0.0 
atom-beautify 0.29.18 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autocomplete-project-paths 2.2.0 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
file-icons 2.1.3 
filesize 2.0.4 
git-plus 7.4.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
language-ejs 0.4.0 
language-pug 0.0.21 
language-stylus 0.2.0 
linter 2.1.2 
linter-eslint 8.1.5 
linter-ui-default 1.2.2 
merge-conflicts 1.4.4 
multi-cursor 2.1.5 
pigments 0.39.1 
project-plus 0.9.0 
sort-lines 0.14.0 
sorter 1.1.0 
split-diff 1.3.0 
todo-show 1.11.0 
```

**Comment by akonwi** [comment]
Without steps to reproduce, I'm not sure how what to do about this.
