### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of null

### ISSUE THREAD

**Issue by lordmuffin** [akonwi/git-plus#652]
Pulled down a new repo and tried switching branches

Steps to reproduce:

1. Clone Repo
2. Try and change brancehs

Stack Trace:

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243

TypeError: Cannot read property 'webkitMatchesSelector' of null
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:243:26)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at /packages/git-plus/lib/git-plus.coffee:230:27)
    at HTMLDivElement.dispatch (/packages/git-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/git-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:06.5.0 core:save (input.hidden-input)
     -6:04.1.0 command-palette:toggle (input.hidden-input)
     -6:02.8.0 core:move-down (input.hidden-input)
     -6:02.6.0 core:move-right (input.hidden-input)
     -6:02.5.0 core:move-down (input.hidden-input)
     -6:02.1.0 core:confirm (input.hidden-input)
     -6:02.1.0 git-plus:commit-all-and-push (input.hidden-input)
     -6:00.0 core:save (input.hidden-input)
     -1:31.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-cform-yaml 0.4.1 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
compare-files 0.8.0 
date 1.2.2 
git-plus 7.5.0 
git-projects 1.17.0 
intentions 1.1.2 
language-powershell 4.0.0 
language-yaml-cloudformation 0.3.1 
linter 2.1.4 
linter-js-cloudformation-yaml 2.2.1 
linter-js-yaml 1.2.7 
linter-ui-default 1.2.3 
material-ui 1.0.10 
multi-cursor 2.1.5 
persistent-undo 1.2.0 
project-manager 3.3.4 
sync-settings 0.8.1 
```

**Comment by lordmuffin** [comment]
Relaunching Atom resolved this, still wanted to report it for you guys.

**Comment by akonwi** [comment]
Thanks! I'll keep an eye out for similar errors

**Comment by shellbryson** [comment]
Also received this error today. It appeared after switching branches externally from Atom, but have been unable to replicate after an Atom restart.
