### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by Vivalldi** [akonwi/git-plus#655]
Steps to reproduce:

1. Simply click the current branch button in the lower right.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.2

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of null
    at CommandLogger.module.exports.CommandLogger.logCommand (/app.asar/node_modules/notifications/lib/command-logger.js:81:38)
    at /app.asar/node_modules/notifications/lib/command-logger.js:33:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at /packages/git-plus/lib/git-plus.coffee:229:27)
    at HTMLDivElement.dispatch (/packages/git-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/git-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.23 
busy-signal 1.4.1 
code-peek 1.4.18 
css-declaration-sorter 1.0.0 
docblockr 0.9.4 
flexbox-snippets 0.3.0 
git-plus 7.7.0 
intentions 1.1.2 
language-assembly 0.7.1 
language-spacebars 0.2.2 
language-twig 1.6.3 
linter 2.1.4 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.3 
merge-conflicts 1.4.4 
meteor-api 2.20.0 
seti-ui 1.7.0 
```

**Comment by richard8a** [comment]
+1. Started receiving this error when I turned on the auto-fetch feature in git-plus.
