### ISSUE TITLE
Uncaught TypeError: treeView.serialize is not a function

### ISSUE THREAD

**Issue by BigZolo** [akonwi/git-plus#661]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.8.0

### Stack Trace

Uncaught TypeError: treeView.serialize is not a function

```
At C:\Users\nazoltan\.atom\packages\git-plus\lib\context-package-finder.coffee:6

TypeError: treeView.serialize is not a function
    at Object.get (/packages/git-plus/lib/context-package-finder.coffee:6:16)
    at module.exports (/packages/git-plus/lib/models/context/git-pull-context.coffee:7:6)
    at /packages/git-plus/lib/git-plus.coffee:172:86)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -1:55.7.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -1:51.1.0 core:move-down (input.hidden-input)
     -1:48 core:move-up (input.hidden-input)
     -1:47.3.0 core:confirm (input.hidden-input)
     -1:47.3.0 git-plus-context:pull (div.tool-panel.tree-view)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-json 5.5.0 
build 0.67.0 
build-powershell 0.10.1 
busy 0.7.0 
busy-signal 1.4.1 
es-identifier-highlight 0.4.3 
git-log 0.4.1 
git-plus 7.8.0 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-log 1.8.0 
language-markdown 0.22.0 
language-nagios 0.2.0 
language-powershell 4.0.0 
language-tsql 0.19.0 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-json-lint 0.1.1 
linter-markdown 4.0.1 
linter-pug-lint 0.2.0 
linter-ui-default 1.5.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.5 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
open_in_cmd 0.6.1 
pigments 0.39.1 
pretty-json 1.6.3 
project-manager 3.3.4 
project-plus 0.9.0 
todo-show 1.11.0 
tree-view-autoresize 2.0.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
xatom-debug 1.6.7 
xatom-debug-chrome 0.7.2 
xatom-debug-nodejs 0.9.1 
```

**Comment by pixilz** [comment]
I believe this should fix your issue:
https://github.com/akonwi/git-plus/pull/664
