### ISSUE TITLE
Uncaught TypeError: uri.match is not a function

### ISSUE THREAD

**Issue by mimoon** [akonwi/git-plus#689]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.2
**Learn IDE Core**: 2.5.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.6
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.9.3

### Stack Trace

Uncaught TypeError: uri.match is not a function

```
At /Applications/Learn IDE.app/Contents/Resources/app.asar/src/project.js:319

TypeError: uri.match is not a function
  at Project.module.exports.Project.resolvePath (/app.asar/src/project.js:319:29)
  at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:410:26)
  at OutputView.show (/packages/git-plus/lib/views/output-view.js:26:22)
  at OutputView.toggle (/packages/git-plus/lib/views/output-view.js:44:41)
  at HTMLAnchorElement.link.onclick (/packages/git-plus/lib/git-plus.coffee:210:55)

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-material-ui 2.0.4 
atom-typescript 11.0.3 
autocomplete-json 5.5.0 
cssnano 1.1.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
Hydrogen 1.14.1 
javascript-snippets 1.2.1 
language-babel 2.65.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.4 
linter-sass-lint 1.7.4 
linter-tslint 1.5.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
minimap 4.28.2 
monokai 0.24.0 
monokai-seti 0.9.0 
nitrogen 0.1.12 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
pigments 0.39.1 
qolor 0.4.1 
script 3.15.0 
set-syntax 0.3.2 
seti-ui 1.8.0 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by akonwi** [comment]
Without steps to reproduce, this issue is not helpful

**Comment by hosea1008** [comment]
I got the same error too, in Ubuntu Kylin 14.04 LTS. When I click the git+ button, this may happen, also, I cannot use the commit.
