### ISSUE TITLE
Uncaught Error: Callback was already called.

### ISSUE THREAD

**Issue by tomaszheflik** [akonwi/git-plus#691]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.9.3

### Stack Trace

Uncaught Error: Callback was already called.

```
At /Users/i326883/.atom/packages/git-plus/node_modules/async/lib/async.js:43

Error: Callback was already called.
    at /packages/git-plus/node_modules/async/lib/async.js:43:36
    at /packages/git-plus/node_modules/async/lib/async.js:771:17
    at /packages/atom-linter-node-dependencies/src/walk-dir.js:32:25
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
  3x -0:44.4.0 core:move-down (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:31.7.0 docblockr:parse-enter (input.hidden-input)
     -0:31.7.0 editor:newline (input.hidden-input)
     -0:31.1.0 core:paste (input.hidden-input)
     -0:20.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.46 
atom-beautify 0.30.3 
atom-linter-node-dependencies 1.5.0 
atom-nodejs-snippets 1.5.0 
atom-shell-commands 1.5.0 
busy-signal 1.4.3 
docblockr 0.10.5 
git-plus 7.9.3 
go-debug 1.4.3 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-docker 1.1.8 
language-groovy 0.7.0 
linter 2.2.0 
linter-jshint 3.1.2 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.2 
minimap 4.28.2 
node-debugger 1.10.1 
nodejs-snippets 2.0.2 
pretty-json 1.6.3 
```

**Comment by akonwi** [comment]
without steps to reproduce, this issue doesn't mean much
