### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Sites/ftp/widgetservices/bellis/css'

### ISSUE THREAD

**Issue by HaRd3sT1** [akonwi/git-plus#734]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.10.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/hard3st1/Sites/ftp/widgetservices/bellis/css'

```
At /Users/hard3st1/.atom/packages/git-plus/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/hard3st1/Sites/ftp/widgetservices/bellis/css'
    at Object.fs.mkdirSync (fs.js:895:18)
    at Function.sync (/packages/git-plus/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:358:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:373:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:194:7)
    at Parser._write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Parser.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
  3x -0:10.5.0 core:close (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-css-clean 2.24.1 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
autocomplete-modules 1.12.0 
double-tag 1.1.0 
expand-region 0.4.0 
git-plus 7.10.2 
remote-ftp 2.1.4 
```

**Comment by akonwi** [comment]
Can you include steps to reproduce this?
