### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'setFlexScale' of undefined

### ISSUE THREAD

**Issue by jdanbrown** [akonwi/git-plus#738]
Steps to reproduce:
1. Configure: `openInPane: true`, `splitPane: Down`
1. Split vertically and create a few tabs on both sides
1. Run `git-plus:commit` to open a new pane item (below) with the commit editor
1. Move the commit editor (pane item) to a different pane that already has some pane items, e.g. drag-drop into one of the splits
1. Save (with or without commit msg, e.g. do without to avoid creating a commit)
1. Observe that the entire pane containing the commit msg item gets destroyed, which leaves behind a blank area where it used to be, and this corrupts the workspace in that it persists after restart
1. Sometimes, you can also observe this stacktrace in the js console (not sure when or why):

```
Uncaught (in promise) TypeError: Cannot read property 'setFlexScale' of undefined
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:231:22)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:197:27)
    at /Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:240:30
    at wrapped (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.destroy (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1037:24)
    at destroyCommitEditor (/Users/danb/.atom/packages/git-plus/lib/models/git-commit.coffee:58:42)
    at /Users/danb/.atom/packages/git-plus/lib/models/git-commit.coffee:80:5
    at <anonymous>
```

Problem:
- https://github.com/akonwi/git-plus/blob/267a06e/lib/models/git-commit.coffee#L58
- I think that `pane.destroy()` is unsafe here, since it destroys all of the items in the pane containing the git commit item (and leaves a blank area and corrupted workspace in its wake), and we should do `paneItem.destroy()` instead, which delegates to the user's choice of "Remove Empty Panes" in atom "Core" settings for whether the containing pane is closed when our commit msg item gets closed as the only and last item in the pane

And here's the only other similar `.destroy()` call that I could find:
- https://github.com/akonwi/git-plus/blob/267a06e/lib/models/git-commit-amend.coffee#L110

PR on its way.

**Comment by jdanbrown** [comment]
PR: https://github.com/akonwi/git-plus/pull/739
