### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop/O_WORKSPACE/WORKSPACE/WORXSITE/HRX/...

### ISSUE THREAD

**Issue by oscarrock** [akonwi/git-plus#744]
[Enter steps to reproduce:]

Creating folder and a file inside that folder with remote-ftp pluggin

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 7.10.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/oscarrico/Desktop/O_WORKSPACE/WORKSPACE/WORXSITE/HRX/HRXv2/webservices/reports'

```
At /Users/oscarrico/.atom/packages/git-plus/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/oscarrico/Desktop/O_WORKSPACE/WORKSPACE/WORXSITE/HRX/HRXv2/webservices/reports'
    at Object.fs.mkdirSync (fs.js:895:18)
    at Function.sync (/packages/git-plus/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:797:12
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1073:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:194:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -3:43.8.0 core:confirm (input.hidden-input)
     -3:25.2.0 remote-ftp:delete-selected (li.file.entry.list-item.selected)
     -3:19.1.0 remote-ftp:add-folder (li.directory.entry.list-nested-item.expanded.selected)
  2x -3:17 core:backspace (input.hidden-input)
     -3:16.5.0 core:confirm (input.hidden-input)
     -3:09.5.0 remote-ftp:add-file (li.directory.entry.list-nested-item.collapsed.selected)
  6x -3:05.9.0 core:backspace (input.hidden-input)
     -2:59.6.0 core:confirm (input.hidden-input)
     -2:35.5.0 core:cut (input.hidden-input)
     -2:29.2.0 core:backspace (input.hidden-input)
  2x -2:23.5.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:26.8.0 core:save (input.hidden-input)
     -0:48.5.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.1.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -0:16.2.0 remote-ftp:add-file (li.directory.entry.list-nested-item.expanded.selected)
     -0:09.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
angularjs 0.5.3 
atom-beautify 0.32.5 
atom-ternjs 0.18.3 
atom-typescript 12.5.1 
autoclose-html 0.23.0 
autocomplete-ionic-framework 0.2.2 
autocomplete-modules 2.0.0 
browser-plus 0.0.98 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.3.0 
css-color-underline 1.0.1 
environment 1.3.1 
firewatch-syntax 1.1.1 
genesis-ui 0.5.0 
git-plus 7.10.2 
git-time-machine 2.0.1 
html-entities 0.4.0 
Hydrogen 2.5.0 
hyperclick 0.1.5 
ionic-preview 0.7.0 
language-babel 2.85.0 
language-cfml 0.23.0 
linter 2.2.0 
local-history 4.3.1 
minimap 4.29.8 
oceanic-next 1.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
qolor 0.4.2 
remote-ftp 2.2.0 
seti-ui 1.10.0 
split-diff 1.5.2 
titanium-alloy 0.14.6 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
turbo-javascript 1.4.0 
webbox-color 0.5.9 
```

**Comment by akonwi** [comment]
Can you provide steps to reproduce?
