### ISSUE TITLE
When pushing, got TypeError: this.input.forEach is not a function

### ISSUE THREAD

**Issue by drgnkpr** [akonwi/git-plus#759]
**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.1.0

### Stack Trace

Uncaught TypeError: this.input.forEach is not a function

```
At /Users/xidong/.atom/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:205

TypeError: this.input.forEach is not a function
    at Filter.forEach (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:139:18)
    at Filter.toHtml (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:129:12)
    at Entry.render (/packages/git-plus/lib/views/output-view/Root.js:114:69)
    at ig (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:157:144)
    at hg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:156:393)
    at pg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:163:15)
    at Rg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:193:380)
    at Sg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:194:274)
    at Xg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:206:121)
    at Yg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:205:174)
    at If (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:201:307)
    at Object.enqueueSetState (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:131:223)
    at Root.E.setState (/packages/git-plus/node_modules/react/cjs/react.production.min.js:13:224)
    at /packages/git-plus/lib/views/output-view/Root.js:162:16
    at /packages/git-plus/lib/activity-logger.js:32:18
    at Set.forEach (<anonymous>)
    at /packages/git-plus/lib/activity-logger.js:31:32
```

### Commands

```
  2x -1:16.4.0 blur (input.hidden-input)
     -1:16 git-plus:menu (input.hidden-input)
  3x -1:15.9.0 blur (input.hidden-input)
     -1:14.7.0 core:confirm (input.hidden-input)
  8x -1:14.7.0 blur (input.hidden-input)
     -1:13.9.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -1:12 core:backspace (input.hidden-input)
 21x -1:04.6.0 blur (input.hidden-input)
     -0:34.4.0 core:backspace (input.hidden-input)
  2x -0:31.2.0 core:move-right (input.hidden-input)
  5x -0:28.4.0 core:backspace (input.hidden-input)
     -0:20.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:19.3.0 ex-mode:open (input.hidden-input)
  3x -0:19.3.0 blur (input.hidden-input)
     -0:18.8.0 core:confirm (input.hidden-input)
 11x -0:18.8.0 blur (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.11 
ex-mode 0.18.0 
file-icons 2.1.24 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 8.1.0 
hyperclick 0.1.5 
indent-guide-improved 1.4.13 
kite 0.104.0 
python-indent 1.1.6 
python-tools 0.6.9 
vim-mode-plus 1.34.0 
```

**Comment by pziewiec** [comment]
the same error :-(

**Comment by GitJer** [comment]
Same here.
