### ISSUE TITLE
Uncaught TypeError: this.input.forEach is not a function

### ISSUE THREAD

**Issue by buggsdummy** [akonwi/git-plus#760]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Linux Mint
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.1.0

### Stack Trace

Uncaught TypeError: this.input.forEach is not a function

```
At /home/vpha200/.atom/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:205

TypeError: this.input.forEach is not a function
    at Filter.forEach (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:139:18)
    at Filter.toHtml (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:129:12)
    at Entry.render (/packages/git-plus/lib/views/output-view/Root.js:114:69)
    at ig (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:157:144)
    at hg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:156:393)
    at pg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:163:15)
    at Rg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:193:380)
    at Sg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:194:274)
    at Xg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:206:121)
    at Yg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:205:174)
    at If (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:201:307)
    at Object.enqueueSetState (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:131:223)
    at Root.E.setState (/packages/git-plus/node_modules/react/cjs/react.production.min.js:13:224)
    at /packages/git-plus/lib/views/output-view/Root.js:162:16
    at /packages/git-plus/lib/activity-logger.js:32:18
    at Set.forEach (<anonymous>)
    at /packages/git-plus/lib/activity-logger.js:31:32
```

### Commands

```
     -9:15.7.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  2x -0:55 git-plus:menu (input.hidden-input)
  3x -0:43.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
git-plus 8.1.0 
```

**Comment by ashthespy** [comment]
Same issue:
[Enter steps to reproduce:]

1. Have two git projects open
2. Try and make a commit

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.1.0


### Stack Trace

Uncaught TypeError: this.input.forEach is not a function

```
At C:\Users\Ash\.atom\packages\git-plus\node_modules\react-dom\cjs\react-dom.production.min.js:205

TypeError: this.input.forEach is not a function
    at Filter.forEach (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:139:18)
    at Filter.toHtml (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:129:12)
    at Entry.render (/packages/git-plus/lib/views/output-view/Root.js:114:69)
    at ig (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:157:144)
    at hg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:156:393)
    at pg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:163:15)
    at Rg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:193:380)
    at Sg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:194:274)
    at Xg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:206:121)
    at Yg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:205:174)
    at If (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:201:307)
    at Object.enqueueSetState (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:131:223)
    at Root.E.setState (/packages/git-plus/node_modules/react/cjs/react.production.min.js:13:224)
    at /packages/git-plus/lib/views/output-view/Root.js:162:16
    at /packages/git-plus/lib/activity-logger.js:32:18
    at Set.forEach (<anonymous>)
    at /packages/git-plus/lib/activity-logger.js:31:32
```

### Commands

```
     -1:16.2.0 intentions:highlight (input.hidden-input)
     -1:16.1.0 core:save (input.hidden-input)
     -1:02.4.0 intentions:highlight (input.hidden-input)
     -1:02.3.0 core:save (input.hidden-input)
     -0:26 intentions:highlight (input.hidden-input)
     -0:25.7.0 command-palette:toggle (input.hidden-input)
  5x -0:24.7.0 core:backspace (input.hidden-input)
     -0:22.7.0 editor:consolidate-selections (input.hidden-input)
     -0:22.7.0 core:cancel (input.hidden-input)
     -0:22 git-plus:menu (input.hidden-input)
     -0:20.6.0 editor:consolidate-selections (input.hidden-input)
     -0:20.6.0 core:cancel (input.hidden-input)
     -0:20 intentions:highlight (input.hidden-input)
     -0:19.9.0 command-palette:toggle (input.hidden-input)
     -0:18.3.0 core:confirm (input.hidden-input)
     -0:18.3.0 editor:OpenTerminal (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-latex 0.8.5 
atom-live-server 2.3.0 
atom-typescript 12.6.3 
busy-signal 1.4.3 
docblockr 0.13.7 
file-icons 2.1.25 
git-plus 8.1.0 
highlight-selected 0.14.0 
intentions 1.1.5 
language-batchfile 0.7.5 
language-docker 1.1.8 
language-matlab 0.2.1 
language-pug 0.0.22 
language-rust 0.4.12 
linter 2.2.0 
linter-eslint 8.4.1 
linter-js-standard 6.0.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pdf-view 0.71.0 
remote-ftp 2.2.0 
script 3.18.1 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.12.1 
```

**Comment by ashthespy** [comment]
[Enter steps to reproduce:]

1. Have multiple git projects open 
2. Commit 

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.1.0


### Stack Trace

Uncaught TypeError: this.input.forEach is not a function

```
At C:\Users\Ash\.atom\packages\git-plus\node_modules\react-dom\cjs\react-dom.production.min.js:205

TypeError: this.input.forEach is not a function
    at Filter.forEach (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:139:18)
    at Filter.toHtml (/packages/git-plus/node_modules/ansi-to-html/lib/ansi_to_html.js:129:12)
    at Entry.render (/packages/git-plus/lib/views/output-view/Root.js:114:69)
    at ig (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:157:144)
    at hg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:156:393)
    at pg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:163:15)
    at Rg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:193:380)
    at Sg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:194:274)
    at Xg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:206:121)
    at Yg (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:205:174)
    at If (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:201:307)
    at Object.enqueueSetState (/packages/git-plus/node_modules/react-dom/cjs/react-dom.production.min.js:131:223)
    at Root.E.setState (/packages/git-plus/node_modules/react/cjs/react.production.min.js:13:224)
    at /packages/git-plus/lib/views/output-view/Root.js:162:16
    at /packages/git-plus/lib/activity-logger.js:32:18
    at Set.forEach (<anonymous>)
    at /packages/git-plus/lib/activity-logger.js:31:32
```

### Commands

```
     -4:25.6.0 core:paste (input.hidden-input)
     -4:25.2.0 core:save (input.hidden-input)
     -2:31.5.0 intentions:highlight (input.hidden-input)
     -2:31.3.0 git-plus:menu (input.hidden-input)
     -2:26.1.0 intentions:highlight (input.hidden-input)
     -2:26 core:paste (input.hidden-input)
     -2:25.1.0 intentions:highlight (input.hidden-input)
     -2:25 core:undo (input.hidden-input)
  4x -2:23.3.0 core:backspace (input.hidden-input)
     -2:06.9.0 core:move-right (input.hidden-input)
     -2:05.5.0 docblockr:parse-enter (input.hidden-input)
     -2:05.5.0 editor:newline (input.hidden-input)
     -2:04.6.0 intentions:highlight (input.hidden-input)
     -2:04.5.0 core:save (input.hidden-input)
     -0:49.6.0 intentions:highlight (input.hidden-input)
     -0:49.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-latex 0.8.5 
atom-live-server 2.3.0 
atom-typescript 12.6.3 
busy-signal 1.4.3 
docblockr 0.13.7 
file-icons 2.1.25 
git-plus 8.1.0 
highlight-selected 0.14.0 
intentions 1.1.5 
language-batchfile 0.7.5 
language-docker 1.1.8 
language-matlab 0.2.1 
language-protobuf 0.7.1 
language-pug 0.0.22 
language-rust 0.4.12 
linter 2.2.0 
linter-eslint 8.4.1 
linter-js-standard 6.0.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pdf-view 0.71.0 
remote-ftp 2.2.0 
script 3.18.1 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.12.1 
```

**Comment by richard-scott** [comment]
I get this just having one project open not multiple projects.

**Comment by HimalayanSage** [comment]
Just one project and tab open and got this on the cmd-w after entering the commit msg
