### ISSUE TITLE
[QUESTION] Failed to activate the git-plus package

### ISSUE THREAD

**Issue by Rix** [akonwi/git-plus#768]
I got an error everytime I start atom: (already tried 'apm install' in package folder)

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
git-plus: 8.1.0

Error: Can't register a command with non-function callback.
    at CommandRegistry.module.exports.CommandRegistry.add (<embedded>:21889:21)
    at Object.activate (/home/mehmetb/.atom/packages/git-plus/lib/git-plus.js:517:44)
    at Package.module.exports.Package.activateNow (<embedded>:69761:25)
    at <embedded>:69733:38
    at Package.module.exports.Package.measure (<embedded>:69607:21)
    at <embedded>:69726:32
    at Package.module.exports.Package.activate (<embedded>:69723:40)
    at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:23715:40)
    at <embedded>:23696:35
    at Config.module.exports.Config.transactAsync (<embedded>:20767:24)
    at PackageManager.module.exports.PackageManager.activatePackages (<embedded>:23691:25)
    at PackageManager.module.exports.PackageManager.activate (<embedded>:23673:52)
    at <embedded>:1081:36

Steps to reproduce:
1. Start Atom

**Comment by akonwi** [comment]
I think I'm using new atom features not supported in your version. The latest version of atom stable is 1.32 and you're on 1.20. Is there a reason you haven't updated yet?

**Comment by Rix** [comment]
Because I am using Ubuntu 16.04.5 version, and v1.20 seems the most recent version in the repo. However, when I install the 1.32.2, problem seems to be fixed. Thanks.

**Comment by nnabuihegabriel** [comment]
The same error pops up on my system each time i launch my atom and my version is 1.38.1 and i can't connect my atom to github i have been stocked on it for three days

**Comment by akonwi** [comment]
@nnabuihegabriel can you share the message and stack trace that you see?

**Comment by MishchenkoA** [comment]
Error: Cannot find module '../git-es'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155156)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:53:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at Object.<anonymous> (/home/mishchenko_a/.atom/packages/git-plus/lib/views/tree-view-branches.ts:4:18)
    at Object.<anonymous> (/home/mishchenko_a/.atom/packages/git-plus/lib/views/tree-view-branches.ts:74:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .ts] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at Object.<anonymous> (/home/mishchenko_a/.atom/packages/git-plus/lib/git-plus.js:7:25)
    at Object.<anonymous> (/home/mishchenko_a/.atom/packages/git-plus/lib/git-plus.js:620:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:686762)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3428177)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3416311)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3416089)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3413720)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3415949)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3415892)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:381112)
    at /usr/share/atom/resources/app/static/<embedded>:11:934678
    at r (/usr/share/atom/resources/app/static/<embedded>:11:929284)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1119363)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1119517)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1118119)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by 4current** [comment]
I was directed to this issue by the error pane.
[Enter steps to reproduce:]

1. start atom
2. wait

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Linux Mint
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.7.1


### Stack Trace

Failed to activate the git-plus package

```
At Unexpected token import

SyntaxError: Unexpected token import
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146949)
    at Object.value [as .ts] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/git-plus/lib/git-plus.js:7:25)
    at /packages/git-plus/lib/git-plus.js:620:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:686762)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3428177)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3416311)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3416089)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3413720)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3415949)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3415892)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:381112)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:380728)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:330844)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:380678)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:380296)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:708814)
```

### Commands

```
```

### Non-Core Packages

```
git-plus 8.7.1 
```

**Comment by akonwi** [comment]
I wonder if something was borked during the update. @4current @MishchenkoA can y'all uninstall the package, restart atom, and install it again?
