### ISSUE TITLE
Plugin not getting installed with atom snaps

### ISSUE THREAD

**Issue by araviaravi** [akonwi/git-plus#773]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Unable to install the plugin

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

I am using Ubuntu 18.04

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

I have problem in this package

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

NA

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

[Description of issue here]

Steps to reproduce:
```
aravind@comp:/var/www/html/ats$ apm install git-plus
Installing git-plus to /home/aravind/.atom/packages ✗

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aravind/.atom/.apm/_logs/2018-12-17T16_00_56_767Z-debug.log
```

`0 info it worked if it ends with ok
1 verbose cli [ '/snap/atom/207/usr/share/atom/resources/app/apm/bin/node',
1 verbose cli   '/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/aravind/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/aravind/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/git-plus/versions/8.2.1/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.11',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 1ad124d9662eee76
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/git-plus/versions/8.2.1/tarball 2860ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/git-plus/versions/8.2.1/tarball fetched in 2871ms
9 timing stage:loadCurrentTree Completed in 2993ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule git-plus@8.2.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/ansi-to-html 168ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/@types%2fatom 171ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/atom-babel6-transpiler 171ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/@babel%2fpolyfill 174ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/@types%2freact 174ms (from cache)
22 silly pacote range manifest for @types/atom@^1.31.0 fetched in 177ms
23 silly resolveWithNewModule @types/atom@1.31.0 checking installable status
24 silly pacote range manifest for atom-babel6-transpiler@^1.2.0 fetched in 177ms
25 silly resolveWithNewModule atom-babel6-transpiler@1.2.0 checking installable status
26 silly pacote range manifest for @babel/polyfill@^7.0.0-beta.51 fetched in 181ms
27 silly resolveWithNewModule @babel/polyfill@7.0.0 checking installable status
28 silly pacote range manifest for @types/react@^16.7.13 fetched in 180ms
29 silly resolveWithNewModule @types/react@16.7.17 checking installable status
30 http fetch GET 200 https://registry.npmjs.org/ansi-to-html/-/ansi-to-html-0.4.2.tgz 11ms (from cache)
31 silly fetchPackageMetaData error for ansi-to-html@^0.4.1 zlib: unexpected end of file
32 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-class-properties 191ms (from cache)
33 silly pacote range manifest for babel-plugin-transform-class-properties@^6.24.1 fetched in 193ms
34 silly resolveWithNewModule babel-plugin-transform-class-properties@6.24.1 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread 34ms (from cache)
36 silly fetchPackageMetaData error for babel-plugin-transform-object-rest-spread@^6.26.0 Unexpected end of JSON input while parsing near '...2810f7d67b4256","tarb'
37 http fetch GET 304 https://registry.npmjs.org/babel-preset-flow 76ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/babel-preset-react 76ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/fuzzaldrin 44ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/fs-plus 62ms (from cache)
41 http fetch GET 304 https://registry.npmjs.org/classnames 78ms (from cache)
42 silly pacote range manifest for babel-preset-flow@^6.23.0 fetched in 81ms
43 silly resolveWithNewModule babel-preset-flow@6.23.0 checking installable status
44 silly pacote range manifest for babel-preset-react@^6.24.1 fetched in 81ms
45 silly resolveWithNewModule babel-preset-react@6.24.1 checking installable status
46 silly pacote range manifest for fuzzaldrin@^1.2.0 fetched in 51ms
47 silly resolveWithNewModule fuzzaldrin@1.2.0 checking installable status
48 silly pacote range manifest for fs-plus@^2.2.0 fetched in 68ms
49 silly resolveWithNewModule fs-plus@2.10.1 checking installable status
50 silly pacote range manifest for classnames@^2.2.6 fetched in 84ms
51 silly resolveWithNewModule classnames@2.2.6 checking installable status
52 http fetch GET 304 https://registry.npmjs.org/babel-preset-env 97ms (from cache)
53 silly fetchPackageMetaData error for babel-preset-env@^1.7.0 Unexpected end of JSON input while parsing near '...7.0.0-alpha.12","babe'
54 http fetch GET 304 https://registry.npmjs.org/linkify-urls 24ms (from cache)
55 silly fetchPackageMetaData error for linkify-urls@^2.0.0 Unexpected end of JSON input while parsing near '...719f83ea763a24f3bf07d'
56 http fetch GET 304 https://registry.npmjs.org/underscore-plus 43ms (from cache)
57 silly pacote range manifest for underscore-plus@^1.6.6 fetched in 45ms
58 silly resolveWithNewModule underscore-plus@1.6.8 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/react 51ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/react-dom 51ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/typescript 54ms (from cache)
62 silly pacote range manifest for react@^16.6.3 fetched in 102ms
63 silly resolveWithNewModule react@16.6.3 checking installable status
64 silly pacote range manifest for typescript@^3.2.2 fetched in 99ms
65 silly resolveWithNewModule typescript@3.2.2 checking installable status
66 silly pacote range manifest for react-dom@^16.6.3 fetched in 101ms
67 silly resolveWithNewModule react-dom@16.6.3 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/atom-ts-transpiler 366ms (from cache)
69 silly pacote range manifest for atom-ts-transpiler@^1.5.2 fetched in 367ms
70 silly resolveWithNewModule atom-ts-transpiler@1.5.2 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 878ms (from cache)
72 silly pacote range manifest for atom-space-pen-views@^2.0.3 fetched in 879ms
73 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/atom-select-list 2025ms (from cache)
75 silly pacote range manifest for atom-select-list@^0.7.1 fetched in 2026ms
76 silly resolveWithNewModule atom-select-list@0.7.2 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/atom-notify 6221ms (from cache)
78 silly pacote range manifest for atom-notify@^1.1.0 fetched in 6223ms
79 silly resolveWithNewModule atom-notify@1.1.0 checking installable status
80 timing stage:rollbackFailedOptional Completed in 1ms
81 timing stage:runTopLevelLifecycles Completed in 9242ms
82 silly saveTree apm-install-dir-1181117-19568-htghmt.8axdr
82 silly saveTree `-- git-plus@8.2.1
82 silly saveTree   +-- @babel/polyfill@7.0.0
82 silly saveTree   +-- @types/atom@1.31.0
82 silly saveTree   +-- @types/react@16.7.17
82 silly saveTree   +-- atom-babel6-transpiler@1.2.0
82 silly saveTree   +-- atom-notify@1.1.0
82 silly saveTree   +-- atom-select-list@0.7.2
82 silly saveTree   +-- atom-space-pen-views@2.2.0
82 silly saveTree   +-- atom-ts-transpiler@1.5.2
82 silly saveTree   +-- babel-plugin-transform-class-properties@6.24.1
82 silly saveTree   +-- babel-preset-flow@6.23.0
82 silly saveTree   +-- babel-preset-react@6.24.1
82 silly saveTree   +-- classnames@2.2.6
82 silly saveTree   +-- fs-plus@2.10.1
82 silly saveTree   | `-- underscore-plus@1.6.8
82 silly saveTree   +-- fuzzaldrin@1.2.0
82 silly saveTree   +-- react-dom@16.6.3
82 silly saveTree   +-- react@16.6.3
82 silly saveTree   +-- typescript@3.2.2
82 silly saveTree   `-- underscore-plus@1.6.8
83 verbose stack ZlibError: zlib: unexpected end of file
83 verbose stack     at Zlib.(anonymous function).onerror (/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:131:21)
83 verbose stack     at Unzip.write (/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:255:31)
83 verbose stack     at Unzip.flush (/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:222:10)
83 verbose stack     at Unzip.end (/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:229:10)
83 verbose stack     at Object.end (/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
83 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
83 verbose stack     at Object.onceWrapper (events.js:313:30)
83 verbose stack     at emitNone (events.js:111:20)
83 verbose stack     at PassThrough.emit (events.js:208:7)
83 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
83 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
83 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
84 verbose cwd /tmp/apm-install-dir-1181117-19568-htghmt.8axdr
85 verbose Linux 4.15.0-42-generic
86 verbose argv "/snap/atom/207/usr/share/atom/resources/app/apm/bin/node" "/snap/atom/207/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/aravind/.atom/.apm/.apmrc" "--userconfig" "/home/aravind/.atom/.apmrc" "install" "https://www.atom.io/api/packages/git-plus/versions/8.2.1/tarball" "--runtime=electron" "--target=2.0.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
87 verbose node v8.9.3
88 verbose npm  v6.2.0
89 error code Z_BUF_ERROR
90 error errno -5
91 error zlib: unexpected end of file
92 verbose exit [ -5, true ]
`

**Comment by akonwi** [comment]
I'm not really sure what caused this error and this is the first time I've seen an error like that. It looks like an npm issue and a google search yielded [this stackoverflow thread with solutions](https://stackoverflow.com/questions/48739985/npm-err-code-z-buf-error-when-install). I suggest you try the solutions there and see if that resolves this for you.

**Comment by araviaravi** [comment]
I am not sure. I don't have npm installed in the pc. I am new to npm.

**Comment by akonwi** [comment]
Unfortunately I don't have a linux environment similar to yours to replicate this. I'm unfamiliar with snaps too. You may not have `npm` installed but atom has `npm` bundled in.

Did you try [this](https://stackoverflow.com/a/48747635/1416369)? You'll want to `rm -rf /home/aravind/.atom/packages/git-plus/node_modules` and then rather than an `npm install` you can just retry the command to install git-plus

**Comment by araviaravi** [comment]
I have removed eitire git-plus folder. But still not working. I have not installed npm in my pc. This is something problem in atom or git-plus.

**Comment by araviaravi** [comment]
Ok I have solved it. I have moved entire .atom folder in home. It worked for me. Please close this issue.
